//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBM.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecord
    {
        public long RecordId { get; set; }
        public string CustomerName { get; set; }
        public string DealerName { get; set; }
        public string DealerContactNo { get; set; }
        public string MechanicName { get; set; }
        public string MechanicContactNo { get; set; }
        public string ServiceName { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public double TotalPrice { get; set; }
        public string LicensePlate { get; set; }
        public int DealerId { get; set; }
        public int CustomerId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
