//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBM.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDealer
    {
        public int DealerId { get; set; }
        public string DealerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ZipCode { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public bool IsActive { get; set; }
        public string Password { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual tblAppointment tblAppointment { get; set; }
        public virtual tblMechanic tblMechanic { get; set; }
        public virtual tblService tblService { get; set; }
    }
}
