//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBM.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobCard
    {
        public int JobCardId { get; set; }
        public int MechanicId { get; set; }
        public int AppointmentId { get; set; }
        public double TotalPrice { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Note { get; set; }
    
        public virtual tblAppointment tblAppointment { get; set; }
        public virtual tblMechanic tblMechanic { get; set; }
    }
}
