//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBM.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMechanic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMechanic()
        {
            this.tblJobCards = new HashSet<tblJobCard>();
        }
    
        public int MechanicId { get; set; }
        public string MechanicName { get; set; }
        public string ContactNo { get; set; }
        public string Make { get; set; }
        public string EmailId { get; set; }
        public bool isActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int DealerId { get; set; }
    
        public virtual tblDealer tblDealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJobCard> tblJobCards { get; set; }
    }
}
